[package]
name = "Flow"
version = "1.0.0"
authors = []

[addresses]
flow_addr = "0x1234"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }

[dependencies.TestCoins]
git = 'https://github.com/pontem-network/test-coins.git'
rev = 'main'

[dev-dependencies]
